{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "FireAnt RESTFUL API",
    "description": "Tài li?u d?c t? FireAnt RESTFUL API v1.0.0"
  },
  "host": "restv2.fireant.vn",
  "schemes": [
    "https"
  ],
  "paths": {
    "/academy/subjects": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y danh sách ch? d? khóa h?c",
        "operationId": "Academy_GetCourseSubjects",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/subjects/{subjectId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y thông tin ch? d? khóa h?c",
        "operationId": "Academy_GetCourseSubject",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/{courseId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y thông tin khóa h?c theo ID",
        "operationId": "Academy_GetCourse",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/levels": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y danh sách t?t c? c?p d? c?a các khóa h?c",
        "operationId": "Academy_GetAllCoursesLevel",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y danh sách khóa h?c",
        "operationId": "Academy_GetCourses",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/recordCount": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y s? lu?ng khóa h?c",
        "operationId": "Academy_GetCoursesCount",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/{courseID}/thumbnail": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y ?nh d?i di?n c?a khóa h?c",
        "operationId": "Academy_GetCourseImage"
      }
    },
    "/academy/courses/{courseId}/lessons": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y danh sách bài gi?ng c?a khóa h?c",
        "operationId": "Academy_GetLessons",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/{courseId}/isEnrolled": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Ki?m tra xem user dã dang ký khóa h?c hay chua",
        "operationId": "Academy_CheckEnrollment",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/lessons/{lessonId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y thông tin bài gi?ng theo ID",
        "operationId": "Academy_GetLesson",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/news": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y danh sách tin t?c",
        "operationId": "Academy_GetNews",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/news/{newsId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y thông tin c?a tin t?c theo ID",
        "operationId": "Academy_GetNews",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/news/recordCount": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y s? lu?ng tin t?c",
        "operationId": "Academy_GetNewsCount",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/news/{newsId}/thumbnail": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y ?nh d?i di?n c?a tin",
        "operationId": "Academy_GetNewsThumbnail"
      }
    },
    "/academy/classes/{classId}/teachers": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y danh sách gi?ng viên c?a l?p h?c",
        "operationId": "Academy_GetTeacherAssignments",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y danh sách các l?p h?c",
        "operationId": "Academy_GetClasses",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/{classId}/schedule": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y thông tin l?ch h?c",
        "operationId": "Academy_GetCourseSchedules",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/ownedClasses": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y danh sách l?p h?c c?a tôi",
        "operationId": "Academy_GetOwnedClass",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/ownedClasses/{classId}/meeting": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y thông tin d?y tr?c tuy?n",
        "operationId": "Academy_GenerateOwnedSignature",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/ownedClasses/{classId}/schedules/{scheduleId}/status": {
      "put": {
        "tags": [
          "Academy"
        ],
        "summary": "C?p nh?t tr?ng thái bu?i h?c",
        "operationId": "Academy_UpdateScheduleStatus",
        "security": [
          {
            "oauth2": [
              "academy-write"
            ]
          }
        ]
      }
    },
    "/academy/classes/enrolledClasses": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y danh sách l?p h?c dã dang ký",
        "operationId": "Academy_GetEnrolledClass",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/enrolledClasses/{classId}/meeting": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y thông tin h?c tr?c tuy?n",
        "operationId": "Academy_GenerateEnrolledSignature",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy": {
      "post": {
        "tags": [
          "Academy"
        ],
        "summary": "Ðang ký khóa h?c",
        "operationId": "Academy_Enroll",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/enrollments/{enrollmentId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "L?y thông tin dang ký khóa h?c",
        "operationId": "Academy_GetEnrollment",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/{enrollmentId}": {
      "put": {
        "tags": [
          "Academy"
        ],
        "summary": "Duy?t don hàng dang ký khóa h?c",
        "operationId": "Academy_ProcessEnrollment",
        "security": [
          {
            "oauth2": [
              "academy-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/bank-account/{accountId}": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Tr? v? thông tin chuy?n kho?n ti?n.",
        "operationId": "Accounts_BankAccount",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Tr? v? danh sách tài kho?n t?i công ty ch?ng khoán c?a user.",
        "operationId": "Accounts_Accounts",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/state": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "L?y tr?ng thái tài kho?n t?i công ty ch?ng khoán",
        "operationId": "Accounts_AccountState",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/state": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "L?y tr?ng thái tài kho?n t?i công ty ch?ng khoán",
        "operationId": "Accounts_AccountState",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/admin/user-info": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "L?y thông tin user theo id",
        "operationId": "Admin_GetUserInfo",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/admin/block-user": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Block 1 user",
        "operationId": "Admin_BlockUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/admin/yesterday-new-users": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Danh sách user m?i dang ký hôm tru?c",
        "operationId": "Admin_GetYesterdayNewUsers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/admin/upload-banner": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Upload ?nh banner qu?ng cáo vào NAS server",
        "operationId": "Admin_UploadBanner",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/admin/upload-ads-json": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Upload file ads.json vào NAS server",
        "operationId": "Admin_UploadAdsJson",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/admin/upload-image": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Upload ?nh vào NAS server",
        "operationId": "Admin_UploadImage",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/authentication/anonymous-login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Ðang nh?p n?c danh",
        "operationId": "Authentication_AnonymousLogin"
      }
    },
    "/authentication/login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Ðang nh?p b?ng m?t kh?u",
        "operationId": "Authentication_Login"
      }
    },
    "/authentication/apple-login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Ðang nh?p Apple",
        "operationId": "Authentication_AppleLogin"
      }
    },
    "/authentication/google-login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Ðang nh?p Google",
        "operationId": "Authentication_GoogleLogin"
      }
    },
    "/authentication/facebook-login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Ðang nh?p Facebook",
        "operationId": "Authentication_FacebookLogin"
      }
    },
    "/authentication/registration": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Ðang ký tài kho?n",
        "operationId": "Authentication_Register"
      }
    },
    "/authentication/password-reset": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Ð?t l?i m?t kh?u",
        "operationId": "Authentication_ForgotPassword"
      }
    },
    "/authentication/email-confirmation": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "G?i email xác nh?n tài kho?n",
        "operationId": "Authentication_SendConfirmEmail"
      }
    },
    "/authentication/refresh-token": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Refresh token",
        "operationId": "Authentication_RefreshToken"
      }
    },
    "/bonds/categories": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "L?y danh sách các danh m?c trái phi?u",
        "operationId": "Bond_GetCategories",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/filter": {
      "post": {
        "tags": [
          "Bond"
        ],
        "summary": "L?c và tìm ki?m trái phi?u",
        "operationId": "Bond_FilterBonds"
      }
    },
    "/bonds/issuer/{symbol}": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "L?y danh sách trái phi?u theo mã t? ch?c phát hành",
        "operationId": "Bond_GetBondsBySymbol",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/{bondCode}": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "L?y thông tin chi ti?t m?t mã trái phi?u",
        "operationId": "Bond_GetBondDetail",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/{bondCode}/cashflow": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "L?y l?ch dòng ti?n tuong lai c?a trái phi?u",
        "operationId": "Bond_GetBondFutureCashFlow",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/stats/issuers/top-debt": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Top doanh nghi?p có du n? trái phi?u l?n nh?t",
        "operationId": "Bond_GetTopIssuersByDebt",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/stats/bonds/high-yield": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Danh sách trái phi?u có lãi su?t cao nh?t",
        "operationId": "Bond_GetHighYieldBonds",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/stats/bonds/maturing-soon": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Danh sách trái phi?u s?p dáo h?n",
        "operationId": "Bond_GetBondsMaturingSoon",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/stats/industries": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Th?ng kê quy mô phát hành theo ngành ngh? (ICB)",
        "operationId": "Bond_GetIndustryStatistics",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/brokers": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Tr? v? danh sách công ty ch?ng khoán",
        "operationId": "Brokers_Brokers"
      }
    },
    "/brokers/{brokerId}/link-user-url": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y liên k?t dùng d? k?t n?i tài kho?n t?i công ty ch?ng khoán v?i tài kho?n FireAnt.",
        "operationId": "Brokers_LinkUserUrl",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/open-account-url": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y liên k?t dùng d? m? tài kho?n t?i công ty ch?ng khoán.",
        "operationId": "Brokers_OpenAccountUrl",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/users/{identityNumber}": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y tên tài kho?n t?i công ty ch?ng khoán theo s? ch?ng minh thu",
        "operationId": "Brokers_GetBrokerUserName",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/job-names": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y danh sách công vi?c.",
        "operationId": "Brokers_GetJobNames",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/job-positions": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y danh sách v? trí công vi?c.",
        "operationId": "Brokers_GetJobPositions",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/referrer-info": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y thông tin ngu?i gi?i thi?u t?i công ty ch?ng khoán.",
        "operationId": "Brokers_GetReferrerInfo",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/banks": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y danh sách ngân hàng.",
        "operationId": "Brokers_GetBanks",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/cif-branches/{branch}": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y danh sách ngân hàng.",
        "operationId": "Brokers_GetCIFBranches",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/kyc-required": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "C?n KYC tru?c d? có th? giao d?ch",
        "operationId": "Brokers_KycRequired",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/welcome-link": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y welcome link.",
        "operationId": "Brokers_GetWelcomeLink",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/common-banners": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "L?y common banners.",
        "operationId": "Brokers_GetBanners",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/webhook": {
      "post": {
        "tags": [
          "Brokers"
        ],
        "summary": "Webhook nh?n tr?ng thái t? CTCK.",
        "operationId": "Brokers_BrokerWebhook"
      }
    },
    "/broker-users": {
      "get": {
        "tags": [
          "BrokerUsers"
        ],
        "summary": "Tr? v? danh sách user ch?ng khoán dã k?t n?i v?i tài kho?n FireAnt",
        "operationId": "BrokerUsers_BrokerUsers",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}": {
      "delete": {
        "tags": [
          "BrokerUsers"
        ],
        "summary": "Xóa user ch?ng khoán dã k?t n?i v?i tài kho?n FireAnt",
        "operationId": "BrokerUsers_DeleteBrokerUser",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/chat/notify": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "G?i thông báo",
        "operationId": "Chat_Notify"
      }
    },
    "/chat/images": {
      "post": {
        "tags": [
          "Chat"
        ],
        "summary": "Upload ?nh cho tin nh?n",
        "operationId": "Chat_UpdateImage",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/chat/images/{key}": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "L?y ?nh trong thông di?p",
        "operationId": "Chat_GetChatImage"
      }
    },
    "/events/search": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Tìm ki?m s? ki?n",
        "operationId": "Events_Search",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/executions": {
      "get": {
        "tags": [
          "Executions"
        ],
        "summary": "Tr? v? danh sách l?nh kh?p trong phiên c?a 1 mã ch?ng khoán",
        "operationId": "Executions_Executions",
        "security": [
          {
            "oauth2": [
              "orders-read"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/is-register": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Check if an account is already registered",
        "operationId": "Fmarket_CheckAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/register-account": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create new Fmarket account",
        "operationId": "Fmarket_RegisterAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/get-account-info": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve Fmarket’s account detail",
        "operationId": "Fmarket_GetAccountInfo",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/link-account/create": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create linked fmarket account",
        "operationId": "Fmarket_CreateLinkAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/link-account/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm linked fmarket account",
        "operationId": "Fmarket_ConfirmLinkAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/get-access-code": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get accessCode to login to web",
        "operationId": "Fmarket_GetAccessCode",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/trading-contract-list": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve Investor’s trading contract list",
        "operationId": "Fmarket_GetTradingContractList",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/esign/create": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Only user have isAllowSign=true in trading contract response can sign",
        "operationId": "Fmarket_CreateSignFmarketContract",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/esign/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm sign",
        "operationId": "Fmarket_ConfirmESign",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/estimate-purchase": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Calculate estimation of volume/fee for purchase order",
        "operationId": "Fmarket_EstimatePurchaseOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-purchase-order/request": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create purchase order",
        "operationId": "Fmarket_CreatePurchaseOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/v2/orders/create-purchase-order/request": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create purchase order",
        "operationId": "Fmarket_CreatePurchaseOrderV2",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-purchase-order/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm purchase order",
        "operationId": "Fmarket_ConfirmPurchaseOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/v2/orders/create-purchase-order/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm purchase order",
        "operationId": "Fmarket_ConfirmPurchaseOrderV2",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/estimate-sale": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Calculate estimation of amount/fee for sale order",
        "operationId": "Fmarket_EstimateSaleOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-sale-order/request": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create sale order",
        "operationId": "Fmarket_CreateSaleOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-sale-order/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm sale order",
        "operationId": "Fmarket_ConfirmSaleOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/get-destination-products": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get list of destination product for convert",
        "operationId": "Fmarket_GetListOfDestinationProduct",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/estimate-convert": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Calculate estimation of amount/fee/tax for convert order",
        "operationId": "Fmarket_EstimateConvertOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-convert-order/request": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create convert order",
        "operationId": "Fmarket_CreateConvertOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-convert-order/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm convert order",
        "operationId": "Fmarket_ConfirmConvertOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/cancel-order": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Cancel order (if supported, please check field: allowed_cancel=true)",
        "operationId": "Fmarket_CancelOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/get-order-detail": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve order detail",
        "operationId": "Fmarket_GetOrderDetail",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/filter-orders": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Query list of orders",
        "operationId": "Fmarket_FilterOrders",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/filter-transactions": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve transaction list",
        "operationId": "Fmarket_FilterTransactions",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/assets/filter-asset-funds": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve asset funds",
        "operationId": "Fmarket_FilterAssetFunds",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/assets/filter-assets": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve assets",
        "operationId": "Fmarket_FilterAssets",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/markets/get-product-detail": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve Fmarket’s product detail",
        "operationId": "Fmarket_GetProductDetail",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/markets/filter-products": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Query list of products",
        "operationId": "Fmarket_FilterProducts",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/markets/issuer-list": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get list issuers",
        "operationId": "Fmarket_GetIssuers",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/provinces": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get province list",
        "operationId": "Fmarket_GetProvinces",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/nationalities": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get nationality  list",
        "operationId": "Fmarket_GetNationalities",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/place-of-issue-id-list": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get place of issue id list",
        "operationId": "Fmarket_GetPlaceOfIssueIDList",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/banks": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get bank list",
        "operationId": "Fmarket_GetBanks",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/get-nav-history": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get Product NAV History",
        "operationId": "Fmarket_GetProductNavHistory",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/hashtags/search": {
      "get": {
        "tags": [
          "HashTags"
        ],
        "summary": "Tìm ki?m ch? d? (hashtag)",
        "operationId": "HashTags_Search",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/hashtags/{hashTagId}/posts": {
      "get": {
        "tags": [
          "HashTags"
        ],
        "summary": "L?y danh sách bài vi?t liên quan t?i 1 ch? d?",
        "operationId": "HashTags_GetHashTagPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/symbols": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "L?y danh sách mã ch?ng khoán trong ngành",
        "operationId": "ICB_GetSymbolsInIndustry",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/statistics": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "L?y th?ng kê d? li?u th?i di?m hi?n t?i c?a ngành",
        "operationId": "ICB_GetCurrentIndustryStats",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/statistics": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "L?y th?ng kê d? li?u th?i di?m hi?n t?i c?a t?t c? ngành",
        "operationId": "ICB_GetAllLatestIndustryStatistics",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/financial-data": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "L?y d? li?u tài chính  c?a ngành",
        "operationId": "ICB_GetFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/financial-data": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "L?y d? li?u tài chính m?i nh?t c?a t?t c? ngành",
        "operationId": "ICB_GetAllLatestIndustryFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/historical-index": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "L?y d? li?u ch? s?  c?a ngành",
        "operationId": "ICB_GetHistoricalIndustryIndex",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/latest-index": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "L?y d? li?u tài chính m?i nh?t c?a t?t c? ngành",
        "operationId": "ICB_GetAllLatestIndustryIndex",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "L?y danh sách ngành",
        "operationId": "ICB_GetIndustries",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/rrg": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "L?y th?ng kê RRG",
        "operationId": "ICB_GetRRG",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/individuals/search": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Tìm ki?m cá nhân",
        "operationId": "Individuals_Search",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/photo": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y ?nh m?t cá nhân",
        "operationId": "Individuals_GetIndividualPhoto"
      }
    },
    "/individuals/{individualId}/posts": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y danh sách bài vi?t liên quan t?i m?t cá nhân",
        "operationId": "Individuals_GetIndividualPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/profile": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y h? so m?t cá nhân",
        "operationId": "Individuals_GetIndividualProfile",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/jobs": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y danh sách công vi?c c?a m?t cá nhân",
        "operationId": "Individuals_GetIndividualJobs",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/assets": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y danh sách tài s?n c?a m?t cá nhân",
        "operationId": "Individuals_GetIndividualAssets",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/relations": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y danh sách m?i quan h? trong gia dình c?a m?t cá nhân",
        "operationId": "Individuals_GetIndividualRelations",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/transactions": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y danh sách giao d?ch mua/bán ch?ng khoán c?a m?t cá nhân",
        "operationId": "Individuals_GetIndividualTransactions",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/richest": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y danh sách ngu?i giàu trên sàn ch?ng khoán",
        "operationId": "Individuals_GetRichestIndividuals",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/gainers": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y danh sách TOP cá nhân tang tài s?n trong ngày trên sàn ch?ng khoán",
        "operationId": "Individuals_GetTopWinnerRichestIndividuals",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/losers": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "L?y danh sách TOP cá nhân gi?m tài s?n trong ngày trên sàn ch?ng khoán",
        "operationId": "Individuals_GetTopLoserRichestIndividuals",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/industries/{industryCode}/historical-stats": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "L?y th?ng kê d? li?u quá kh? c?a ngành",
        "operationId": "Industries_GetHistoricalIndustryStats",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/industries/{industryCode}/current-stats": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "L?y th?ng kê d? li?u th?i di?m hi?n t?i c?a ngành",
        "operationId": "Industries_GetCurrentIndustryStats",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/industries/current-stats": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "L?y th?ng kê d? li?u th?i di?m hi?n t?i c?a t?t c? ngành",
        "operationId": "Industries_GetAllCurrentIndustryStats",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/industries": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "L?y danh sách ngành",
        "operationId": "Industries_GetIndustries",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/industries/{industryCode}/rrg": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "L?y th?ng kê RRG",
        "operationId": "Industries_GetRRG",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/instruments": {
      "get": {
        "tags": [
          "Instruments"
        ],
        "summary": "Tr? danh sách toàn b? mã ch?ng khoán",
        "operationId": "Instruments_AllInstruments"
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/instruments": {
      "get": {
        "tags": [
          "Instruments"
        ],
        "summary": "Tr? danh sách mã ch?ng khoán tài kho?n du?c phép giao d?ch",
        "operationId": "Instruments_Instruments",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "L?y danh sách thu?t ng?",
        "operationId": "Investopedia_GetTerms",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/recordCount": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "L?y s? lu?ng thu?t ng?",
        "operationId": "Investopedia_GetTermsCount",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/search": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "Tìm ki?m thu?t ng? theo t? khóa",
        "operationId": "Investopedia_SearchTerms",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/keywords/recordCount": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "L?y s? lu?ng thu?t ng? theo t? khóa",
        "operationId": "Investopedia_GetTermsByKeywordsCount",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/{termKey}": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "L?y thông tin thu?t ng? theo tên",
        "operationId": "Investopedia_GetTermByName",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/{termId}": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "L?y thông tin thu?t ng? theo ID",
        "operationId": "Investopedia_GetTermById",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/categories": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "L?y danh sách danh m?c thu?t ng?",
        "operationId": "Investopedia_GetInvestopediaCategories",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/categories/{categoryId}": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "L?y thông tin danh m?c thu?t ng?",
        "operationId": "Investopedia_GetInvestopediaCategory",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/ir/contracts": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "L?y t?t c? h?p d?ng IR",
        "operationId": "IR_GetAllContracts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/ir/contracts/{symbol}": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "L?y chi ti?t h?p d?ng IR c?a 1 mã ch?ng khoán",
        "operationId": "IR_GetLastContractBySymbol",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/ir/latest-statistics/{symbol}": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "L?y th?ng kê ho?t d?ng IR c?a 1 mã ch?ng khoán",
        "operationId": "IR_GetLatestIRContractStatistics",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/ir/historical-statistics/{symbol}": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "L?y l?ch s? ho?t d?ng IR c?a 1 mã ch?ng khoán",
        "operationId": "IR_GetHistoricalIRContractStatistics",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/ir/post-statistics/{symbol}": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "L?y th?ng kê ho?t d?ng IR c?a các bài vi?t c?a 1 mã ch?ng khoán",
        "operationId": "IR_GetIRPostStatisticsBySymbol",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/macro-data/types": {
      "get": {
        "tags": [
          "Macro"
        ],
        "summary": "L?y danh sách các lo?i d? li?u vi mô",
        "operationId": "Macro_GetMacroIndicatorTypes",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/macro-data/{type}/info": {
      "get": {
        "tags": [
          "Macro"
        ],
        "summary": "L?y d? li?u vi mô theo lo?i",
        "operationId": "Macro_GetMacroIndicatorInfo",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/me/push-tokens": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Ðang ký token d? push",
        "operationId": "Me_RegisterPushToken",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/recent-symbols": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Ðang ký token d? push",
        "operationId": "Me_UpdateRecentSymbols",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/web-pushs": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "G?i web push",
        "operationId": "Me_SendPush",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/web-pushs-topic": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "G?i web push t?i topic",
        "operationId": "Me_SendPushToTopic",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/push-topic-subscribers": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Ðang ký push topic",
        "operationId": "Me_SubscribeToTopic",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/push-topic-unsubscribers": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "B? dang ký push topic",
        "operationId": "Me_UnsubscribeToTopic",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/emails": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "G?i email",
        "operationId": "Me_SendEmail",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/fbtoken": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y token d? xác th?c, dùng các d?ch v? luu tr? trên Firebase",
        "operationId": "Me_GetFirebaseToken",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/phone-number": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y s? di?n tho?i c?a user",
        "operationId": "Me_GetPhoneNumber",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t s? di?n tho?i c?a user",
        "operationId": "Me_UpdateUserPhoneNumber",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/phone-number/verify": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Xác th?c s? di?n tho?i c?a user",
        "operationId": "Me_VerifyUserPhoneNumber",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/profile": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y h? so c?a 1 user",
        "operationId": "Me_GetUserProfile",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t h? so c?a 1 user",
        "operationId": "Me_UpdateUserProfile",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/settings": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y các thi?t l?p hi?n t?i c?a user",
        "operationId": "Me_GetUserSettings",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t các thi?t l?p c?a user",
        "operationId": "Me_UpdateUserSettings",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/purchased-items": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y thông tin các s?n ph?m ngu?i dùng dã mua",
        "operationId": "Me_GetPurchasedItems",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/account": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y thông tin t?ng h?p tài kho?n c?a user",
        "operationId": "Me_GetUserAccount",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/password": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Ki?m tra tài kho?n dã d?t m?t kh?u chua",
        "operationId": "Me_HasPassword",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Thay d?i m?t kh?u",
        "operationId": "Me_ChangePassword",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Ð?t m?t kh?u",
        "operationId": "Me_SetPassword",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/avatar": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Thay d?i avatar",
        "operationId": "Me_UpdateAvatar",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/authentic": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Ðang ký chính ch?",
        "operationId": "Me_UpdateUserAuthentic",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/extra-info": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t thông tin b? sung cho user",
        "operationId": "Me_UpdateUserExtraInfo",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/posts/stream": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách bài vi?t du?c hi?n th? cho user",
        "operationId": "Me_GetStreamPosts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/posts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách bài vi?t c?a user",
        "operationId": "Me_GetPosts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/blocked-users": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách ngu?i dùng b?n dang block",
        "operationId": "Me_GetBlockedUsers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Block 1 user",
        "operationId": "Me_BlockUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/blocked-users/{blockedUserId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Unblock 1 user",
        "operationId": "Me_UnblockUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/followers": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách ngu?i dang theo dõi b?n",
        "operationId": "Me_GetFollowers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/following": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách ngu?i dùng mà b?n dang theo dõi",
        "operationId": "Me_GetFollowing",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Theo dõi 1 user",
        "operationId": "Me_FollowUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/following/{followedUserId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "B? theo dõi 1 user",
        "operationId": "Me_UnfollowUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/hashtags": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách hashtag dang theo dõi",
        "operationId": "Me_GetUserHashTags",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Theo dõi 1 hashtag",
        "operationId": "Me_FollowHashTag",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/hashtags/{hashTagId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "B? theo dõi 1 hashtag",
        "operationId": "Me_UnfollowHashTag",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/notifications/new": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y s? lu?ng thông báo m?i",
        "operationId": "Me_GetNewNotificationCount",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Reset l?i s? lu?ng thông báo m?i",
        "operationId": "Me_ResetNewNotificationCount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/notifications": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách thông báo",
        "operationId": "Me_GetNotifications",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa h?t thông báo",
        "operationId": "Me_ClearNotifications",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/notifications/unread/{notificationId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Ðánh d?u 1 thông báo là dã d?c",
        "operationId": "Me_MarkNotificationAsRead",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/notifications/unread": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Ðánh d?u t?t c? thông báo là dã d?c",
        "operationId": "Me_MarkAllNotificationsAsRead",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/watchlists/{watchlistID}/posts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y bài vi?t c?a watchlist",
        "operationId": "Me_GetWatchlistPosts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/watchlists": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách watchlist",
        "operationId": "Me_GetWatchlists",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "T?o watchlist",
        "operationId": "Me_CreateWatchlist",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/watchlists/{watchlistId}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y watchlist",
        "operationId": "Me_GetWatchlist",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t watchlist",
        "operationId": "Me_UpdateWatchlist",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa watchlist",
        "operationId": "Me_DeleteWatchlist",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/watchlists/orders": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t th? t? hi?n th? watchlist",
        "operationId": "Me_UpdateWatchlistOrders",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/chart-templates": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách m?u bi?u d?",
        "operationId": "Me_GetChartTemplates",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "T?o m?u bi?u d?",
        "operationId": "Me_CreateChartTemplate",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/following-chart-templates": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách m?u bi?u d? du?c chia s?",
        "operationId": "Me_GetFollowingChartTemplates",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/fireant-chart-templates": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách m?u bi?u d? c?a FireAnt",
        "operationId": "Me_GetFireAntChartTemplates",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/chart-templates/{templateID}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y n?i dung m?u bi?u d?",
        "operationId": "Me_GetChartTemplateContent",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Luu m?u bi?u d?",
        "operationId": "Me_SaveChartTemplate",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa m?u bi?u d?",
        "operationId": "Me_DeleteChartTemplate",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Me"
        ],
        "summary": "Thay d?i thông tin m?u bi?u d?",
        "operationId": "Me_UpdateChartTemplate",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/membership": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y thông tin h?i viên dã dang ký",
        "operationId": "Me_GetUserMembership",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/alerts/notifications": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách thông báo",
        "operationId": "Me_GetAlertNotifications",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t thông báo",
        "operationId": "Me_UpdateAlertNotifications",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/alerts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách c?nh báo",
        "operationId": "Me_GetAlertRegistrations",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm dang ký nh?n c?nh báo",
        "operationId": "Me_AddAlertRegistration",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/alerts/{id}": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t dang ký c?nh báo",
        "operationId": "Me_UpdateAlertRegistration",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa dang ký nh?n c?nh báo",
        "operationId": "Me_DeleteAlertRegistration",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/mobile-alerts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách c?nh báo di?n tho?i",
        "operationId": "Me_GetMobileAlerts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm dang ký nh?n c?nh báo di?n tho?i",
        "operationId": "Me_CreateMobileAlert",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/mobile-alerts/{symbol}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y c?nh báo di?n tho?i v?i 1 mã ch?ng khoán",
        "operationId": "Me_GetMobileAlert",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa dang ký nh?n c?nh báo di?n tho?i",
        "operationId": "Me_DeleteMobileAlert",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/fireant-screeners": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách b? l?c m?u c?a FireAnt",
        "operationId": "Me_GetFireAntScreeners",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/screeners": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách b? l?c",
        "operationId": "Me_GetScreeners",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm b? l?c m?i",
        "operationId": "Me_AddScreener",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/screeners/filter": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Th?c hi?n l?c d?a trên di?u ki?n json",
        "operationId": "Me_Filter",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/screeners/{id}": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t b? l?c",
        "operationId": "Me_UpdateScreener",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa b? l?c",
        "operationId": "Me_DeleteScreener",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/workspaces": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách workspace",
        "operationId": "Me_GetWorkspaces",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm workspace m?i",
        "operationId": "Me_AddWorkspace",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/workspaces/{id}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y tr?ng thái workspace",
        "operationId": "Me_GetWorkspaceState",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "C?p nh?t b? l?c",
        "operationId": "Me_UpdateWorkspace",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa workspace",
        "operationId": "Me_DeleteWorkspace",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/room-invitations/{invitationId}": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Ra quy?t d?nh v?i l?i m?i tham gia nhóm",
        "operationId": "Me_UpdateInvitation",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa l?i m?i tham gia nhóm",
        "operationId": "Me_DeleteInvitation",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/me/permissions/create-room": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Ki?m tra quy?n t?o nhóm c?a ngu?i dùng",
        "operationId": "Me_GetCreateRoomPermission",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/rooms": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách nhóm dang tham gia",
        "operationId": "Me_GetRooms",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/rooms/{roomId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "R?i kh?i nhóm",
        "operationId": "Me_LeaveRoom",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/rooms/{roomId}/nonmember-users": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Danh sách g?i ý ngu?i chua ph?i thành viên nhóm",
        "operationId": "Me_GetNonMemberUsers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/verify-identity": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Xác th?c danh tính (KYC)",
        "operationId": "Me_VerifyIdentity",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/link": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Link tài kho?n dã có t?i công ty ch?ng khoán.",
        "operationId": "Me_LinkBrokerUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/suggest-account-number": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "G?i ý s? tài kho?n t?i công ty ch?ng khoán.",
        "operationId": "Me_SuggestAccountNumber",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/check-suggest-number": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Ki?m tra s? tài kho?n có th? ch?n t?i công ty ch?ng khoán.",
        "operationId": "Me_CheckSuggestNumber",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/econtract": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y thông tin h?p d?ng di?n t? m? tài kho?n t?i CTCK.",
        "operationId": "Me_GetEContractInformation",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/send-otp": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "G?i mã OTP xác th?c email.",
        "operationId": "Me_SendOtpEmail",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/verify-otp": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Xác th?c email b?ng OTP.",
        "operationId": "Me_VerifyOtp",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y tr?ng thái tài kho?n t?i công ty ch?ng khoán.",
        "operationId": "Me_GetBrokerUserStatus",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "T?o tài kho?n t?i công ty ch?ng khoán.",
        "operationId": "Me_CreateBrokerUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/money-account": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y thông tin tài kho?n ti?n c?a ngu?i dùng",
        "operationId": "Me_GetAccount",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/money-transactions": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách giao d?ch ti?n",
        "operationId": "Me_GetTransactions",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "T?o giao d?ch ti?n",
        "operationId": "Me_CreateTransaction",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/banks": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách ngân hàng du?c h? tr?",
        "operationId": "Me_GetBanks",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/bank-accounts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách tài kho?n ngân hàng",
        "operationId": "Me_GetBankAccounts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm tài kho?n ngân hàng",
        "operationId": "Me_AddBankAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/bank-accounts/lookup-name": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Tra c?u tên tài kho?n ngân hàng",
        "operationId": "Me_LookupBankAccountName",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/bank-accounts/{bankAccountId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa tài kho?n ngân hàng",
        "operationId": "Me_RemoveBankAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/mxv/account": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y thông tin tài kho?n hàng hóa MXV",
        "operationId": "Me_GetMXVAccount",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/mxv/orders": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách l?nh giao d?ch hàng hóa MXV",
        "operationId": "Me_GetMXVOrders",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/mxv/positions": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y danh sách v? th? m? hàng hóa MXV",
        "operationId": "Me_GetMXVAccountPositions",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/mxv/account-request": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "L?y yêu c?u t?o tài kho?n giao d?ch hàng hóa MXV",
        "operationId": "Me_GetMXVAccountRequest",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Yêu c?u t?o tài kho?n giao d?ch hàng hóa MXV",
        "operationId": "Me_CreateMXVAccountRequest",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/pin-code": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Ð?i pin code",
        "operationId": "Me_ChangePinCode",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/request-sms-otp": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Yêu c?u g?i mã OTP qua SMS",
        "operationId": "Me_RequestSmsOTP",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/fmarket-account": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "T?o tài kho?n Fmarket",
        "operationId": "Me_CreateFMarketAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/fmarket-account-confirmation": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Xác nh?n liên k?t tài kho?n Fmarket",
        "operationId": "Me_ConfirmLinkFmarketAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/monitoring/status": {
      "get": {
        "tags": [
          "Monitoring"
        ],
        "summary": "Ki?m tra tr?ng thái API",
        "operationId": "Monitoring_Status"
      }
    },
    "/mxv/brokers": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "L?y danh sách Môi gi?i",
        "operationId": "MXV_GetBrokers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/collaborators": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "L?y danh sách C?ng tác viên",
        "operationId": "MXV_GetCollaborators",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/account": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "L?y thông tin chi ti?t tài kho?n MXV",
        "operationId": "MXV_GetAccountDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "T?o tài kho?n MXV (Future, Nano, MXV)",
        "operationId": "MXV_CreateMXVAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/account/status": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "L?y tr?ng thái tài kho?n MXV (Future, Nano, MXV)",
        "operationId": "MXV_GetMXVAccountStatus",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/account/margin-status": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "L?y tr?ng thái ký qu? hi?n t?i",
        "operationId": "MXV_GetMarginStatus",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/account/margin-transactions": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "L?y l?ch s? n?p rút ký qu?",
        "operationId": "MXV_GetMarginTransactions",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/account/deposit-request": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Yêu c?u n?p ti?n vào tài kho?n MXV",
        "operationId": "MXV_DepositRequest",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/account/withdraw-request": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Yêu c?u rút ti?n t? tài kho?n MXV",
        "operationId": "MXV_WithdrawRequest",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/account/transfer-money-request": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Yêu c?u chuy?n ti?n gi?a các tài kho?n Future, Nano, MXV",
        "operationId": "MXV_TransferMoneyRequest",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/account/money-requests": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "L?y l?ch s? yêu c?u n?p/rút/chuy?n ti?n c?a ngu?i dùng",
        "operationId": "MXV_GetMoneyRequests",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/market/commodities": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Qu?n lý hàng hoá",
        "operationId": "MXV_GetCommodities",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/market/commodities/{commodityCode}": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Chi ti?t hàng hoá",
        "operationId": "MXV_GetCommodityDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/market/contracts": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Qu?n lý h?p d?ng",
        "operationId": "MXV_GetContracts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/market/contracts/{contractCode}": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Chi ti?t h?p d?ng",
        "operationId": "MXV_GetContractDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/positions": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Danh sách tr?ng thái m?",
        "operationId": "MXV_GetPositionsOpen",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/positions/settle": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Danh sách tr?ng thái t?t toán",
        "operationId": "MXV_GetPositionsSettle",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/transactions": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Danh sách giao d?ch",
        "operationId": "MXV_GetTrades",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/orders": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Danh sách l?nh",
        "operationId": "MXV_GetOrders",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Ð?t l?nh m?i",
        "operationId": "MXV_PlaceOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/orders/{clientOrderId}": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Chi ti?t l?nh",
        "operationId": "MXV_GetOrderDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "MXV"
        ],
        "summary": "S?a l?nh",
        "operationId": "MXV_ReplaceOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "MXV"
        ],
        "summary": "H?y l?nh",
        "operationId": "MXV_CancelOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/register": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Ðang ký giao hàng v?t ch?t (bên bán)",
        "operationId": "MXV_PhysicalDeliveryRegister",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/cancel": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Hu? dang ký giao hàng v?t ch?t",
        "operationId": "MXV_PhysicalDeliveryCancel",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-receive/register": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Ðang ký nh?n hàng v?t ch?t (bên mua)",
        "operationId": "MXV_PhysicalReceiveRegister",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-receive/cancel": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Hu? dang ký nh?n hàng v?t ch?t",
        "operationId": "MXV_PhysicalReceiveCancel",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/deposit": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Ðang ký luu ký hàng v?t ch?t vào kho (bên bán)",
        "operationId": "MXV_PhysicalDeliveryDeposit",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/cancel-deposit": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Hu? dang ký luu ký hàng v?t ch?t",
        "operationId": "MXV_PhysicalCancelDeposit",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/designated": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Xác nh?n giao hàng v?t ch?t ch? d?nh (bên bán)",
        "operationId": "MXV_PhysicalDeliveryDesignated",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-receive/designated": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Xác nh?n nh?n hàng v?t ch?t ch? d?nh (bên mua)",
        "operationId": "MXV_PhysicalReceiveDesignated",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/history": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "L?y danh sách dang ký giao/nh?n hàng v?t ch?t",
        "operationId": "MXV_GetPhysicalDeliveryHistory",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/history/detail": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "L?y thông tin chi ti?t dang ký giao/nh?n hàng v?t ch?t",
        "operationId": "MXV_GetPhysicalDeliveryDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/registrations": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Truy v?n tr?ng thái dang ký giao/nh?n hàng v?t ch?t",
        "operationId": "MXV_GetPhysicalRegistrations",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/transactions": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Truy v?n tr?ng thái nghia v? giao/nh?n hàng v?t ch?t",
        "operationId": "MXV_GetPhysicalTransactions",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/orders": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Tr? v? danh sách l?nh d?t trong phiên",
        "operationId": "Orders_Orders",
        "security": [
          {
            "oauth2": [
              "orders-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Ð?t l?nh",
        "operationId": "Orders_CreateOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/orders/otp": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Yêu c?u g?i OTP d?t l?nh",
        "operationId": "Orders_SendOtp",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/orders/{orderId}": {
      "put": {
        "tags": [
          "Orders"
        ],
        "summary": "S?a l?nh",
        "operationId": "Orders_EditOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Orders"
        ],
        "summary": "H?y l?nh",
        "operationId": "Orders_DeleteOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/orderHistory": {
      "get": {
        "tags": [
          "OrdersHistory"
        ],
        "summary": "Tr? v? l?ch s? d?t l?nh c?a tài kho?n",
        "operationId": "OrdersHistory_OrderHistory",
        "security": [
          {
            "oauth2": [
              "orders-read"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/orders": {
      "get": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "Tr? v? danh sách l?nh d?t trong phiên",
        "operationId": "OrdersV2_Orders",
        "security": [
          {
            "oauth2": [
              "orders-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "Ð?t l?nh",
        "operationId": "OrdersV2_CreateOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/orders/otp-required": {
      "get": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "C?n OTP d? giao d?ch",
        "operationId": "OrdersV2_OtpRequired",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/orders/otp": {
      "post": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "Yêu c?u g?i OTP d?t l?nh",
        "operationId": "OrdersV2_SendOtp",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/orders/{orderId}": {
      "put": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "S?a l?nh",
        "operationId": "OrdersV2_EditOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "H?y l?nh",
        "operationId": "OrdersV2_DeleteOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/otp/time": {
      "get": {
        "tags": [
          "Otp"
        ],
        "summary": "L?y gi? máy ch? OTP",
        "operationId": "Otp_RequestSmsOTP",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/otp/sms-otp": {
      "get": {
        "tags": [
          "Otp"
        ],
        "summary": "Yêu c?u g?i mã OTP qua SMS",
        "operationId": "Otp_RequestSmsOtp",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/otp/smart-otp": {
      "get": {
        "tags": [
          "Otp"
        ],
        "summary": "L?y thông tin dang ký Smart Otp",
        "operationId": "Otp_GetSmartOtpInfo",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Otp"
        ],
        "summary": "Ðang ký Smart OTP",
        "operationId": "Otp_RegisterSmartOtp",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/positions": {
      "get": {
        "tags": [
          "Positions"
        ],
        "summary": "Tr? v? v? th? m? c?a tài kho?n",
        "operationId": "Positions_Positions",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/positions/{positionId}": {
      "delete": {
        "tags": [
          "Positions"
        ],
        "summary": "Ðóng v? th?",
        "operationId": "Positions_ClosePosition",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/positions": {
      "get": {
        "tags": [
          "PositionsV2"
        ],
        "summary": "Tr? v? v? th? m? c?a tài kho?n",
        "operationId": "PositionsV2_Positions",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/positions/{positionId}": {
      "delete": {
        "tags": [
          "PositionsV2"
        ],
        "summary": "Ðóng v? th?",
        "operationId": "PositionsV2_ClosePosition",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/posts/groups": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách nhóm bài vi?t",
        "operationId": "Posts_GetPostGroups",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/experts": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách chuyên gia",
        "operationId": "Posts_GetExperts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/sources": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách ngu?n tin",
        "operationId": "Posts_GetPostSources",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/feed": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y news feed c?a ngu?i dùng",
        "operationId": "Posts_GetNewsFeed",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách bài vi?t",
        "operationId": "Posts_GetPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Posts"
        ],
        "summary": "Ðang bài vi?t",
        "operationId": "Posts_InsertPost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/popular": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách bài vi?t ph? bi?n",
        "operationId": "Posts_GetPopularPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/livestream": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách livestream",
        "operationId": "Posts_GetLivestreamPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/video": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách bài vi?t video",
        "operationId": "Posts_GetVideoPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/video/top": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách video tiêu di?m",
        "operationId": "Posts_GetTopVideos",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/emagazine": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách bài vi?t emagazine",
        "operationId": "Posts_GetEmagazinePosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/infographic": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách bài vi?t infographic",
        "operationId": "Posts_GetInfographicPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/individuals": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách bài vi?t có d? c?p t?i các cá nhân",
        "operationId": "Posts_GetIndividualRelatedPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/expert-ideas": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách bài vi?t nh?n d?nh chuyên gia",
        "operationId": "Posts_GetExpertIdeas",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/related-posts": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách bài vi?t liên quan t?i 1 bài vi?t",
        "operationId": "Posts_GetRelatedPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/replies": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách bình lu?n c?a 1 bài vi?t",
        "operationId": "Posts_GetReplies",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/replies/{replyPostId}/index": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y th? t? c?a 1 bình lu?n trong danh sách bình lu?n c?a 1 bài vi?t",
        "operationId": "Posts_GetReplyPostIndex",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/likes": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách ngu?i thích 1 bài vi?t",
        "operationId": "Posts_GetLikes",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Posts"
        ],
        "summary": "Thích bài vi?t",
        "operationId": "Posts_LikePost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Posts"
        ],
        "summary": "B? thích bài vi?t",
        "operationId": "Posts_UnlikePost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/{postId}": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y n?i dung bài vi?t",
        "operationId": "Posts_GetPost",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Posts"
        ],
        "summary": "S?a bài vi?t",
        "operationId": "Posts_UpdatePost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Posts"
        ],
        "summary": "Xóa bài vi?t",
        "operationId": "Posts_DeletePost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/livestream-permission": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Ki?m tra quy?n livestream",
        "operationId": "Posts_HasLivestreamPermission",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/kyc-required": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Ki?m tra ngu?i dùng có c?n KYC khi dang bài không",
        "operationId": "Posts_HasPostPermission",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/livestream/start": {
      "put": {
        "tags": [
          "Posts"
        ],
        "summary": "B?t d?u livestream",
        "operationId": "Posts_StartLivestream",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/livestream/stop": {
      "put": {
        "tags": [
          "Posts"
        ],
        "summary": "K?t thúc livestream",
        "operationId": "Posts_StopLivestream",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/images/{imageId}": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y ?nh trong bài vi?t",
        "operationId": "Posts_GetPostImage"
      }
    },
    "/posts/{postId}/abuse-reports": {
      "post": {
        "tags": [
          "Posts"
        ],
        "summary": "Báo cáo x?u bài vi?t",
        "operationId": "Posts_ReportAbuse",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/link-detail": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y preview c?a liên k?t",
        "operationId": "Posts_GetLinkPreview",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/detected-symbols": {
      "post": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách mã ch?ng khoán trong n?i dung bài vi?t c?a liên k?t",
        "operationId": "Posts_GetSymbols",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/popular-symbols/{period}": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "L?y danh sách mã ch?ng khoán du?c chia s? nhi?u",
        "operationId": "Posts_GetPopularSymbols",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/reports/{reportID}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Thông tin v? 1 báo cáo",
        "operationId": "Reports_GetReport",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/reports/search": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Tìm ki?m báo cáo",
        "operationId": "Reports_Search",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/reports/categories": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Danh sách danh m?c báo cáo",
        "operationId": "Reports_GetCategories",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/reports/sources": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Danh sách ngu?n báo cáo",
        "operationId": "Reports_GetSources",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y thông tin v? room",
        "operationId": "Rooms_GetRoom",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "C?p nh?t thông tin nhóm",
        "operationId": "Rooms_UpdateRoomInfo",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Rooms"
        ],
        "summary": "Xóa nhóm",
        "operationId": "Rooms_DeleteRoom",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/top/popular": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y danh sách nhóm ph? bi?n",
        "operationId": "Rooms_GetPopularRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/top/featured": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y danh sách nhóm d?c s?c",
        "operationId": "Rooms_GetFeaturedRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/top/recommended": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y danh sách nhóm du?c khuy?n ngh?",
        "operationId": "Rooms_GetRecommendedRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms": {
      "post": {
        "tags": [
          "Rooms"
        ],
        "summary": "T?o room",
        "operationId": "Rooms_CreateRoom",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/cover-image": {
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "Thay d?i ?nh d?i di?n nhóm",
        "operationId": "Rooms_UpdateRoomCoverImage",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/invitations": {
      "post": {
        "tags": [
          "Rooms"
        ],
        "summary": "G?i l?i m?i",
        "operationId": "Rooms_Invite",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/requests": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y danh sách các yêu c?u tham giá nhóm dang ch?",
        "operationId": "Rooms_GetPendingRequests",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Rooms"
        ],
        "summary": "G?i yêu c?u tham gia nhóm",
        "operationId": "Rooms_SendRequest",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/requests/{requestId}": {
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "Duy?t yêu c?u tham gia nhóm",
        "operationId": "Rooms_UpdateRequest",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Rooms"
        ],
        "summary": "Xóa yêu c?u tham gia nhóm",
        "operationId": "Rooms_DeleteRequest",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/members/{userId}/role": {
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "Gán quy?n cho thành viên",
        "operationId": "Rooms_AssignRole",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/members": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y danh sách thành viên nhóm",
        "operationId": "Rooms_GetMembers",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/members/{userId}": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y thông tin thành viên trong nhóm",
        "operationId": "Rooms_GetMembers",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Rooms"
        ],
        "summary": "Xóa thành viên kh?i nhóm",
        "operationId": "Rooms_RemoveMember",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/blocked-users": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y danh sách ngu?i dùng b? ch?n",
        "operationId": "Rooms_GetBlockedUsers",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Rooms"
        ],
        "summary": "Ch?n ngu?i dùng",
        "operationId": "Rooms_BlockUser",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/blocked-users/{userId}": {
      "delete": {
        "tags": [
          "Rooms"
        ],
        "summary": "B? ch?n ngu?i dùng",
        "operationId": "Rooms_UnblockUser",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/posts": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y danh sách bài vi?t trong nhóm",
        "operationId": "Rooms_GetPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/sticky-posts": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "L?y danh sách bài vi?t dính trong nhóm",
        "operationId": "Rooms_GetStickyPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/posts/{postId}/sticky": {
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "C?p nh?t tr?ng thái dính cho bài vi?t trong nhóm",
        "operationId": "Rooms_UpdateSticky",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/search": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "Tìm ki?m",
        "operationId": "Search_Search",
        "security": [
          {
            "oauth2": [
              "search"
            ]
          }
        ]
      }
    },
    "/search/exact": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "Tìm ki?m chính xác",
        "operationId": "Search_SearchExact",
        "security": [
          {
            "oauth2": [
              "search"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Thông tin mã ch?ng khoán",
        "operationId": "Symbols_GetSymbol",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/search": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Tìm ki?m mã ch?ng khoán",
        "operationId": "Symbols_Search",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/movers": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "TOP c? phi?u bi?n d?ng",
        "operationId": "Symbols_GetTopMovers",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/proprietary-trading-value": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "TOP c? phi?u du?c t? doanh mua/bán",
        "operationId": "Symbols_ProprietaryTradingNetValue",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/contribute-to-index": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "TOP mã ch?ng khoán dóng góp vào index",
        "operationId": "Symbols_TopContributeToIndex",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/posts": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y danh sách bài vi?t liên quan t?i Mã ch?ng khoán",
        "operationId": "Symbols_GetSymbolPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/rooms": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y danh sách nhóm liên quan t?i Mã ch?ng khoán",
        "operationId": "Symbols_GetSymbolRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/historical-quotes": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y giá quá kh? c?a Mã ch?ng khoán",
        "operationId": "Symbols_GetHistoricalQuotes",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/financial-reports": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y báo cáo tài chính tóm t?t c?a doanh nghi?p",
        "operationId": "Symbols_GetSummaryFinancialReports",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/full-financial-reports": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y báo cáo tài chính d?y d? c?a doanh nghi?p",
        "operationId": "Symbols_GetFinancialReports",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/financial-indicators": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y ch? tiêu tài chính c?a doanh nghi?p",
        "operationId": "Symbols_GetFinancialIndicators",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/fundamental": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y thông tin co b?n, quan tr?ng c?a 1 Mã ch?ng khoán",
        "operationId": "Symbols_GetSymbolFundamental",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/profile": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y h? so công ty",
        "operationId": "Symbols_GetInstitutionProfile",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/subsidiaries": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y danh sách công ty con/liên k?t c?a 1 t? ch?c",
        "operationId": "Symbols_GetSubCompanies",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/holders": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y danh sách c? dông l?n c?a 1 t? ch?c",
        "operationId": "Symbols_GetMajorHolders",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/officers": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y danh sách ban lãnh d?o c?a 1 t? ch?c",
        "operationId": "Symbols_GetOfficers",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/holder-transactions": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y danh sách giao d?ch (Mua/Bán) c?a các c? dông l?n (v?i c? phi?u c?a t? ch?c)",
        "operationId": "Symbols_GetMajorHolderTransactions",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/timescale-marks": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y các m?c s? ki?n theo th?i gian (Báo cáo tài chính, C? t?c,...)",
        "operationId": "Symbols_GetTimescaleMarks",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/transactions": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y danh sách giao d?ch (Mua/Bán) c?a t? ch?c",
        "operationId": "Symbols_GetTransactions",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/transactions/{transactionID}": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y chi ti?t 1 giao d?ch",
        "operationId": "Symbols_GetTransaction",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/dividends": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y th?ng kê c? t?c hàng nam",
        "operationId": "Symbols_GetDividends",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/rrg": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y th?ng kê RRG",
        "operationId": "Symbols_GetRRG",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/estimated-price": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y thông tin d?nh giá",
        "operationId": "Symbols_GetEstimatedPrice",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/commodity-contract": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y thông tin chi ti?t h?p d?ng tuong lai hàng hóa phái sinh",
        "operationId": "Symbols_GetCommodityContractInfo",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/commodities/{category}": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y danh sách h?p d?ng tuong lai hàng hóa phái sinh theo danh m?c",
        "operationId": "Symbols_GetCommoditiesByCategory",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/warrant-info": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y thông tin chi ti?t ch?ng quy?n có d?m b?o",
        "operationId": "Symbols_GetWarrantInfo",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/crypto-info": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y thông tin chi ti?t crypto",
        "operationId": "Symbols_GetCryptoInfo",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/financial-data": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y thông tin tài chính d?y d? c?a doanh nghi?p",
        "operationId": "Symbols_GetFullFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/all-financial-data": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y thông tin tài chính d?y d? c?a t?t c? doanh nghi?p",
        "operationId": "Symbols_GetAllFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/financial-data-by-period": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y thông tin tài chính d?y d? c?a doanh nghi?p theo k? báo cáo",
        "operationId": "Symbols_GetFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/dynamic-financial-data": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y thông tin tài chính d?ng d? so sánh gi?a các doanh nghi?p",
        "operationId": "Symbols_GetDynamicFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/bonds": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y danh sách trái phi?u do công ty phát hành",
        "operationId": "Symbols_GetSymbolBonds",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/bonds/{bondCode}": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y chi ti?t m?t trái phi?u c? th? do công ty phát hành",
        "operationId": "Symbols_GetSymbolBondDetail",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/bonds/{bondCode}/cashflow": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "L?y l?ch dòng ti?n tuong lai c?a m?t trái phi?u c? th?",
        "operationId": "Symbols_GetSymbolBondCashFlow",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/profile": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y h? so c?a 1 user",
        "operationId": "Users_GetUserProfile",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/avatar": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y ?nh d?i di?n c?a 1 user",
        "operationId": "Users_GetUserAvatar"
      }
    },
    "/users/active": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y danh sách ngu?i dùng tích c?c",
        "operationId": "Users_GetMostActive",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/most-followed": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y danh sách ngu?i dùng du?c theo dõi nhi?u",
        "operationId": "Users_GetMostFollowed",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/followers": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y danh sách ngu?i dang theo dõi 1 user",
        "operationId": "Users_GetFollowers",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/following": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y danh sách ngu?i dùng mà 1 user dang theo dõi",
        "operationId": "Users_GetFollowing",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/symbols": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y danh sách mã ch?ng khoán quan tâm c?a 1 user",
        "operationId": "Users_GetUserSymbols",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/posts": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y danh sách bài vi?t c?a 1 user",
        "operationId": "Users_GetUserPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/videos": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y danh sách videos c?a 1 user",
        "operationId": "Users_GetUserVideos",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/rooms": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "L?y danh sách nhóm dang tham gia c?a 1 user",
        "operationId": "Users_GetRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "oauth2": {
      "type": "oauth2",
      "description": "OAuth2 Implicit Grant",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.fireant.vn/connect/authorize",
      "scopes": {
        "accounts-read": "Ð?c danh sách tài kho?n giao d?ch ch?ng khoán",
        "accounts-write": "Liên k?t tài kho?n ch?ng khoán",
        "orders-read": "Ð?c danh sách l?nh giao d?ch ch?ng khoán",
        "orders-write": "Ð?t, s?a, h?y l?nh giao d?ch ch?ng khoán",
        "companies-read": "Ð?c thông tin doanh nghi?p",
        "companies-write": "T?o m?i, c?p nh?t, xóa thông tin doanh nghi?p",
        "individuals-read": "Ð?c thông tin cá nhân",
        "individuals-write": "T?o m?i, c?p nh?t, xóa thông tin cá nhân",
        "finance-read": "Ð?c thông tin tài chính",
        "finance-write": "T?o m?i, c?p nh?t, xóa thông tin tài chính",
        "posts-write": "Ðang bài vi?t",
        "posts-read": "L?y n?i dung các bài vi?t c?a c?ng d?ng",
        "symbols-read": "Ð?c thông tin mã ch?ng khoán",
        "symbols-write": "T?o m?i, c?p nh?t, xóa mã ch?ng khoán",
        "users-read": "Ð?c d? li?u công khai c?a ngu?i dùng",
        "user-data-read": "Ð?c t?t c? d? li?u c?a ngu?i dùng hi?n t?i",
        "user-data-write": "C?p nh?t t?t c? d? li?u c?a ngu?i dùng hi?n t?i",
        "search": "Tìm ki?m",
        "academy-read": "Ð?c d? li?u các khóa h?c",
        "academy-write": "Ðang ký khóa h?c",
        "blog-read": "Ð?c d? li?u blog",
        "investopedia-read": "Ð?c d? li?u thu?t ng?",
        "commodities-read": "Ð?c d? li?u hàng hóa phái sinh",
        "all_claims": "All",
        "roles": "Role"
      }
    }
  }
}
