export const GOLD_SOURCE_REGISTRY = Object.freeze([
  {
    id: "bls-release-calendar",
    publisher: "U.S. Bureau of Labor Statistics",
    role: "CPI, PPI and labour release schedule",
    url: "https://www.bls.gov/schedule/news_release/bls.ics",
    tier: "official",
    cadence: "event-driven",
    required: true,
  },
  {
    id: "bls-cpi",
    publisher: "U.S. Bureau of Labor Statistics",
    role: "Latest CPI release",
    url: "https://www.bls.gov/news.release/cpi.nr0.htm",
    tier: "official",
    cadence: "monthly",
    required: true,
  },
  {
    id: "bls-ppi",
    publisher: "U.S. Bureau of Labor Statistics",
    role: "Latest PPI release",
    url: "https://www.bls.gov/news.release/ppi.nr0.htm",
    tier: "official",
    cadence: "monthly",
    required: true,
  },
  {
    id: "bls-employment",
    publisher: "U.S. Bureau of Labor Statistics",
    role: "Latest Employment Situation release",
    url: "https://www.bls.gov/news.release/empsit.nr0.htm",
    tier: "official",
    cadence: "monthly",
    required: true,
  },
  {
    id: "federal-reserve-fomc",
    publisher: "Federal Reserve Board",
    role: "FOMC calendar, statements and minutes",
    url: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    tier: "official",
    cadence: "event-driven",
    required: true,
  },
  {
    id: "bea-releases",
    publisher: "U.S. Bureau of Economic Analysis",
    role: "PCE, GDP and current economic releases",
    url: "https://www.bea.gov/news/current-releases",
    tier: "official",
    cadence: "event-driven",
    required: true,
  },
  {
    id: "treasury-real-yields",
    publisher: "U.S. Department of the Treasury",
    role: "Daily real yield curve",
    url: "https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_real_yield_curve",
    tier: "official",
    cadence: "business-daily",
    required: true,
  },
  {
    id: "cftc-comex-cot",
    publisher: "U.S. Commodity Futures Trading Commission",
    role: "COMEX Gold Commitments of Traders",
    url: "https://www.cftc.gov/dea/futures/deacmxlf.htm",
    tier: "official",
    cadence: "weekly",
    required: true,
  },
  {
    id: "wgc-central-bank-reserves",
    publisher: "World Gold Council",
    role: "Reported central-bank gold reserves",
    url: "https://www.gold.org/goldhub/data/gold-reserves-by-country",
    tier: "industry-authority",
    cadence: "monthly",
    required: false,
  },
  {
    id: "wgc-etf-flows",
    publisher: "World Gold Council",
    role: "Gold ETF holdings and flows",
    url: "https://www.gold.org/goldhub/data/gold-etfs-holdings-and-flows",
    tier: "industry-authority",
    cadence: "weekly/monthly",
    required: false,
  },
]);

export const SOURCE_POLICY = Object.freeze({
  registryVersion: "2026-09-11.1",
  timezone: "Asia/Ho_Chi_Minh",
  dailyRunLocalTime: "06:05",
  publicSummaryOnly: true,
  note: "WGC gated downloads are not scraped; public pages are monitored for provenance and freshness.",
});
